components:
  PreferencesView.vue:
    modules:
      - name: 'GeneralSettings'
  Shops.vue:
    modules:
      - name: 'GeneralSettings'
      - name: 'ShopList'
  Genres.vue:
    modules:
      - name: 'GeneralSettings'
      - name: 'ShopList'
      - name: 'GenreList'
  ShopsNearBy.vue:
    modules:
      - name: 'GeneralSettings'
      - name: 'ShopList'
      - name: 'GenreList'
      - name: 'UserLocation'

modules:
  GeneralSettings:
    extent: 'session'
    fields:
      userId: number
      userName: string
      userPassword: string
      userIntroduce: string
  ShopList:
    extent: 'component'
    fields:
      userId: number
      userName: string
      userPassword: string
      userIntroduce: string
  GenreList:
    extent: 'component'
    fields:
      userId: number
      userName: string
      userPassword: string
      userIntroduce: string
  UserLocation:
    extent: 'component'
    fields:
      userId: number
      userName: string
      userPassword: string
      userIntroduce: string

#  MenuGroup.vue:
#    modules:
#      - name: 'MenuGroup'
#        extent: 'session'
#        fields:
#          groupId: number
#          groupName: string
#          displayOrder: number
#      - name: 'Test'
#        extent: 'session'
#        fields:
#          testId: number
#          testName: string
#          displayOrder: number
#      - name: 'Test'
#        extent: 'session'
#        fields:
#          testId: number
#          testName: string
#          displayOrder: number
#
#  UserProfile.vue:
#    module:
#      name: 'User'
#      extent: 'local'
#      fields:
#        userId: number
#        username: string
#        email: string